apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student
    run: student
  name: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
   metadata:
    labels:
      app: student
   spec:
    containers:
    - image: 10.128.0.12:5000/syedhajirali/studentmaster:${BUILD_NUMBER}
      name: student


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: student
  name: student
  namespace: default
spec:
  ports:
  - nodePort: 35000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: student
  sessionAffinity: None
  type: NodePort
