apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student
    run: student
  name: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
   metadata:
    labels:
      app: student
   spec:
    containers:
    - image: 10.128.0.12:5000/syedhajirali/studentmaster:${BUILD_NUMBER}
      name: student


