apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    run: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
   metadata:
    labels:
      app: frontend
   spec:
    containers:
    - image: 10.128.0.12:5000/syedhajirali/studentMaster:${BUILD_NUMBER}
      name: frontend

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
  - nodePort: 32333
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort
